CREATE TABLE trips(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    truck_id BIGINT NOT NULL REFERENCES trucks(id),
    started_at timestamptz NOT NULL,
    ended_at timestamptz,
    status VARCHAR(50) NOT NULL
                  CHECK(status IN('ACTIVE','COMPLETED'))

);