CREATE TABLE telemetry_records(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    truck_id BIGINT NOT NULL REFERENCES trucks(id),
    trip_id BIGINT REFERENCES trips(id),
    speed DOUBLE PRECISION NOT NULL ,
    rpm INTEGER NOT NULL ,
    fuel DOUBLE PRECISION NOT NULL ,
    gear INTEGER NOT NULL,
    timestamp timestamptz
);