CREATE TABLE driving_events (
             id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
             truck_id BIGINT NOT NULL REFERENCES trucks(id),
             trip_id BIGINT REFERENCES trips(id),

             event_type VARCHAR(50) NOT NULL,

             previous_speed DOUBLE PRECISION NOT NULL,
             current_speed DOUBLE PRECISION NOT NULL,
             speed_difference DOUBLE PRECISION NOT NULL,

             duration_ms BIGINT NOT NULL,
             deceleration DOUBLE PRECISION NOT NULL,
             occurred_at timestamptz NOT NULL
);